### ISSUE TITLE
How it works?

### ISSUE THREAD

**Issue by botsbuzz** [okmttdhr/YoutuVote#31]
Could you explain better how YoutuVote works? It seems very interesting.
Could the user vote his favorite YouTube channels?

Thank you for your effort on this!

**Comment by okmttdhr** [comment]
Sorry for my lateness.

With `YoutuVote`, you can vote for YouTube channels and make the ranking of them (All YouTube channels should belong to Japan or make videos about Japan). I suppose these things below;

- You can vote for YouTube channels as much as you want, which will be the `score` of channels. Channels are ranked by `score`.
- YouTube channels `score` is not the same as `vote` counts, which will be the sum of something like Twitter, Musically, TikTok followers. `YoutuVote` doesn't look up only subscriber counts of YouTube channels, but focuses on a individual power on the internet (it might not be possible to implement that all in a initial phase, though😓 I wanna visualize the `score` other than the activity on YouTube so that you can find which channels are actually nice).
- You can make your own ranking if you vote, that means you can visualize how much spend your `vote` on which channels.

I suppose that users of `YoutuVote` are the male (First of all, I planned to create this app because most of the YouTubers I love are the Japanese male, I wanted to give something valuable for them).
